kind: pipeline
type: ssh
name: deploy to VM

server:
  host: 192.168.56.1
  user: test
  password:
    from_secret: ssh_psw

steps:
- name: deploy
  commands:
  - cd release
  - bash ./rewrite_config.sh
  - bash ./drone_deploy.sh

trigger:
  branch:
  - main
  event:
  - push
  - tag